### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat.Houston#1]
What is this? Please update ReadMe file for more info. Thanks.

**Comment by geekgonecrazy** [comment]
Right now primarily internal tools for releasing(launching) new versions of Rocket.Chat :)

**Comment by rodrigok** [comment]
@mnlbox [readme](https://github.com/RocketChat/Rocket.Chat.Houston/blob/master/README.md) updated thanks.
